In [1]:
#@title Data retrieval
from matplotlib import rcParams
from matplotlib import pyplot as plt
import numpy as np
import os
import sys
sys.path.append(os.path.dirname(os.getcwd()))
from utils.utils import load_data, load_results
from utils.plot_utils import *


rcParams['figure.figsize'] = [20, 4]
rcParams['font.size'] = 15
rcParams['axes.spines.top'] = False
rcParams['axes.spines.right'] = False
rcParams['figure.autolayout'] = True

In [2]:
path_to_results = "search_results.csv"
all_results = load_results(path_to_results)
all_results

,Unnamed: 0,Feature,Window_Size,Brodmann_Area_Number,Min_Frequency,Max_Frequency,Participant_Index,train_score,test_score,Num_points
0,"07/21/2023,22:34:50",cursorX,40,6,8.0,25.0,1,0.00106,0.00280,NaN
1,"07/21/2023,22:46:20",cursorX,100,38,8.0,25.0,1,0.00119,-0.00242,NaN
2,"07/21/2023,22:46:41",cursorX,100,21,8.0,25.0,1,0.00121,-0.00150,NaN
3,"07/21/2023,22:46:56",cursorX,100,47,8.0,25.0,1,0.00128,-0.00519,NaN
4,"07/21/2023,22:47:12",cursorX,100,6,8.0,25.0,1,0.00152,0.00439,NaN
...,...,...,...,...,...,...,...,...,...,...
2714,"07/23/2023,23:38:22",target_radius,12000,6,35.0,42.0,3,0.20316,-0.43491,300.0
2715,"07/23/2023,23:38:50",target_radius,12000,21,35.0,42.0,3,0.15985,-0.56723,300.0
2716,"07/23/2023,23:39:19",target_radius,12000,22,35.0,42.0,3,0.19170,-0.45350,300.0
2717,"07/23/2023,23:39:32",target_radius,12000,37,35.0,42.0,3,0.02398,-0.10825,300.0
2718,"07/23/2023,23:39:46",target_radius,12000,38,35.0,42.0,3,0.06884,-0.01464,300.0